/**
 * @file generate_extra.go
 * @package cli
 * @author Dr.NP <np@herewe.tech>
 * @since 09/06/2026
 */

package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

var (
	extraServers = []string{"fiber", "http", "grpc", "tcp", "udp", "websocket"}
	extraClients = []string{"http", "grpc", "tcp", "udp", "websocket"}
	extraBrokers = []string{"nats", "jetstream", "nsq"}
	extraJobs    = []string{"cron", "ticker"}
)

// firstPositional is reserved for future positional-arg helpers.
// Deliberately kept (see docs/deadcode-report.md P2); not wired yet.
//
//lint:ignore U1000 deliberately kept as extension point
func firstPositional(fsArgs []string) string { return "" }

func generateServerStub(args []string) int {
	fs, gf, err := parseGenerateFlags("generate server", args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sicky generate server: %s\n", err.Error())

		return 1
	}

	if fs.NArg() < 1 {
		fmt.Fprintln(os.Stderr, "sicky generate server: missing server type")
		fmt.Fprintf(os.Stderr, "Valid: %s\n", strings.Join(extraServers, ","))

		return 1
	}

	kind := strings.ToLower(fs.Arg(0))
	ok := false
	for _, v := range extraServers {
		if kind == v || (kind == "ws" && v == "websocket") {
			kind = v
			ok = true
		}
	}

	if !ok {
		fmt.Fprintf(os.Stderr, "sicky generate server: unknown server %q (valid: %s)\n", fs.Arg(0), strings.Join(extraServers, ","))

		return 1
	}

	name := kind
	if fs.NArg() >= 2 {
		name = fs.Arg(1)
	}

	dir := gf.output
	if dir == "" {
		dir = "internal/server"
	}

	content := "// Package server wires a " + kind + " server instance.\n" +
		"// Generated by `sicky generate server " + kind + "`. TODO: fill addresses from config.\n" +
		"package server\n\n" +
		"// " + exportName(name) + "Kind identifies this server wiring.\n" +
		"const " + exportName(name) + "Kind = \"" + kind + "\"\n"

	return writeGuard(filepath.Join(dir, name+".go"), content, gf, "server")
}

func generateClientStub(args []string) int {
	fs, gf, err := parseGenerateFlags("generate client", args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sicky generate client: %s\n", err.Error())

		return 1
	}

	if fs.NArg() < 1 {
		fmt.Fprintln(os.Stderr, "sicky generate client: missing client type")
		fmt.Fprintf(os.Stderr, "Valid: %s\n", strings.Join(extraClients, ","))

		return 1
	}

	kind := strings.ToLower(fs.Arg(0))
	name := kind
	if fs.NArg() >= 2 {
		name = fs.Arg(1)
	}

	dir := gf.output
	if dir == "" {
		dir = "internal/client"
	}

	content := "// Package client wraps an outbound " + kind + " client.\n" +
		"// Generated by `sicky generate client`. TODO: dial + retry policy.\n" +
		"package client\n\n" +
		"// " + exportName(name) + "Kind identifies this client wiring.\n" +
		"const " + exportName(name) + "Kind = \"" + kind + "\"\n"

	return writeGuard(filepath.Join(dir, name+".go"), content, gf, "client")
}

func generateServiceStub(args []string) int {
	fs, gf, err := parseGenerateFlags("generate service", args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sicky generate service: %s\n", err.Error())

		return 1
	}

	if fs.NArg() < 1 {
		fmt.Fprintln(os.Stderr, "sicky generate service: missing service type (standard, mcp, interactive)")

		return 1
	}

	kind := strings.ToLower(fs.Arg(0))
	switch kind {
	case "standard", "mcp", "interactive":
	default:
		fmt.Fprintf(os.Stderr, "sicky generate service: unknown service %q\n", kind)

		return 1
	}

	dir := gf.output
	if dir == "" {
		dir = "internal/service"
	}

	content := "// Package service wires a " + kind + " service.\n" +
		"// Generated by `sicky generate service`. TODO: register servers/brokers/jobs.\n" +
		"package service\n\n" +
		"// Kind identifies this service wiring.\n" +
		"const Kind = \"" + kind + "\"\n"

	return writeGuard(filepath.Join(dir, kind+".go"), content, gf, "service")
}

func generateBrokerStub(args []string) int {
	fs, gf, err := parseGenerateFlags("generate broker", args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sicky generate broker: %s\n", err.Error())

		return 1
	}

	if fs.NArg() < 1 {
		fmt.Fprintln(os.Stderr, "sicky generate broker: missing broker (nats, jetstream, nsq)")

		return 1
	}

	kind := strings.ToLower(fs.Arg(0))
	ok := false
	for _, v := range extraBrokers {
		if kind == v {
			ok = true
		}
	}

	if !ok {
		fmt.Fprintf(os.Stderr, "sicky generate broker: unknown broker %q\n", fs.Arg(0))

		return 1
	}

	dir := gf.output
	if dir == "" {
		dir = "internal/broker"
	}

	content := "// Package broker subscribes to " + kind + " topics.\n" +
		"// Generated by `sicky generate broker`. TODO: implement subscribe handlers.\n" +
		"// NOTE: check broker.Message.Format/Scan errors; Mime must be set before Scan.\n" +
		"package broker\n\n" +
		"// " + exportName(kind) + "Topic is the default topic.\n" +
		"const " + exportName(kind) + "Topic = \"" + kind + ".default\"\n"

	return writeGuard(filepath.Join(dir, kind+".go"), content, gf, "broker")
}

func generateJobStub(args []string) int {
	fs, gf, err := parseGenerateFlags("generate job", args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sicky generate job: %s\n", err.Error())

		return 1
	}

	if fs.NArg() < 1 {
		fmt.Fprintln(os.Stderr, "sicky generate job: missing job (cron, ticker)")

		return 1
	}

	kind := strings.ToLower(fs.Arg(0))
	if kind != "cron" && kind != "ticker" {
		fmt.Fprintf(os.Stderr, "sicky generate job: unknown job %q\n", fs.Arg(0))

		return 1
	}

	name := kind
	if fs.NArg() >= 2 {
		name = fs.Arg(1)
	}

	dir := gf.output
	if dir == "" {
		dir = "internal/job"
	}

	content := "// Package job implements a " + kind + " background job.\n" +
		"// Generated by `sicky generate job`. Handlers return error; set Task.Timeout watchdog.\n" +
		"package job\n\n" +
		"// " + exportName(name) + " runs the job body. Return nil on success.\n" +
		"func " + exportName(name) + "() error { return nil }\n"

	return writeGuard(filepath.Join(dir, name+".go"), content, gf, "job")
}

func generateMiddlewareStub(args []string) int {
	fs, gf, err := parseGenerateFlags("generate middleware", args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sicky generate middleware: %s\n", err.Error())

		return 1
	}

	if fs.NArg() < 1 {
		fmt.Fprintln(os.Stderr, "sicky generate middleware: missing middleware name")

		return 1
	}

	name := fs.Arg(0)
	dir := gf.output
	if dir == "" {
		dir = "internal/middleware"
	}

	content := "// Package middleware holds HTTP middlewares (fiber + net/http).\n" +
		"// Generated by `sicky generate middleware`. Keep CORS deny-by-default.\n" +
		"package middleware\n\n" +
		"// " + exportName(name) + " is a middleware placeholder.\n" +
		"func " + exportName(name) + "() struct{} { return struct{}{} }\n"

	return writeGuard(filepath.Join(dir, name+".go"), content, gf, "middleware")
}

func generateProtoFile(args []string) int {
	fs, gf, err := parseGenerateFlags("generate proto", args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sicky generate proto: %s\n", err.Error())

		return 1
	}

	if fs.NArg() < 1 {
		fmt.Fprintln(os.Stderr, "sicky generate proto: missing proto name")

		return 1
	}

	name := strings.ToLower(fs.Arg(0))
	dir := gf.output
	if dir == "" {
		dir = "proto"
	}

	svc := exportName(name)
	content := "syntax = \"proto3\";\n\npackage " + name + ";\n\noption go_package = \"./;pb\";\n\n" +
		"service " + svc + " {\n  rpc Ping (PingRequest) returns (PingReply);\n}\n\n" +
		"message PingRequest {\n  string message = 1;\n}\n\n" +
		"message PingReply {\n  string message = 1;\n}\n"

	return writeGuard(filepath.Join(dir, name+".proto"), content, gf, "proto")
}

func generateConfigFile(args []string) int {
	fs, gf, err := parseGenerateFlags("generate config", args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sicky generate config: %s\n", err.Error())

		return 1
	}

	_ = fs
	nc := &newContext{
		Name:           detectProjectName(),
		Module:         detectModule(),
		Type:           "standard",
		Servers:        []string{"fiber", "grpc"},
		Registry:       "local",
		Tracer:         "none",
		DockerRegistry: "docker.io",
	}

	nc.AppName = nc.Name + ".example.sicky"
	nc.ExportedName = exportName(nc.Name)
	if err := normalizeNewContext(nc); err != nil {
		fmt.Fprintf(os.Stderr, "sicky generate config: %s\n", err.Error())

		return 1
	}

	content, err := renderProjectTemplate("template/project/standard/config.json.gotmpl", nc)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sicky generate config: %s\n", err.Error())

		return 1
	}

	outputPath := "config.json"
	if gf.output != "" {
		outputPath = filepath.Join(gf.output, "config.json")
	}

	return writeGuard(outputPath, content, gf, "config")
}

func generateDockerFiles(args []string) int {
	_, gf, err := parseGenerateFlags("generate docker", args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sicky generate docker: %s\n", err.Error())

		return 1
	}

	nc := &newContext{
		Name:           detectProjectName(),
		Module:         detectModule(),
		DockerRegistry: "docker.io",
	}

	nc.AppName = nc.Name + ".example.sicky"
	nc.ExportedName = exportName(nc.Name)
	dockerfile, err := renderProjectTemplate("template/project/shared/Dockerfile.gotmpl", nc)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sicky generate docker: %s\n", err.Error())

		return 1
	}

	ignore, err := renderProjectTemplate("template/project/shared/dockerignore.gotmpl", nc)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sicky generate docker: %s\n", err.Error())

		return 1
	}

	dir := gf.output
	if dir == "" {
		dir = "."
	}

	if rc := writeGuard(filepath.Join(dir, "Dockerfile"), dockerfile, gf, "docker"); rc != 0 {
		return rc
	}

	return writeGuard(filepath.Join(dir, ".dockerignore"), ignore, gf, "docker")
}

func generateK8sFiles(args []string) int {
	fs, gf, err := parseGenerateFlags("generate k8s", args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sicky generate k8s: %s\n", err.Error())

		return 1
	}

	name := detectProjectName()
	if fs.NArg() >= 1 {
		name = fs.Arg(0)
	}

	dir := gf.output
	if dir == "" {
		dir = "deploy"
	}

	deploy := "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: " + name + "\n" +
		"spec:\n  replicas: 2\n  selector:\n    matchLabels:\n      app: " + name + "\n" +
		"  template:\n    metadata:\n      labels:\n        app: " + name + "\n" +
		"    spec:\n      containers:\n      - name: svc\n" +
		"        image: " + name + ":latest\n        ports:\n        - containerPort: 3000\n" +
		"        - containerPort: 8888\n"
	svc := "apiVersion: v1\nkind: Service\nmetadata:\n  name: " + name + "\n" +
		"spec:\n  selector:\n    app: " + name + "\n  ports:\n  - name: http\n    port: 3000\n" +
		"  - name: manager\n    port: 8888\n"
	if rc := writeGuard(filepath.Join(dir, "deployment.yaml"), deploy, gf, "k8s"); rc != 0 {
		return rc
	}

	return writeGuard(filepath.Join(dir, "service.yaml"), svc, gf, "k8s")
}

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * End:
 * vim600: sw=4 ts=4 fdm=marker
 * vim<600: sw=4 ts=4
 */
